services:
  postgres:
    image: postgres:13
    container_name: 'surveybara-challange-db'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5434}:5432
